In [1]:
import pandas as pd

df = pd.read_csv("Electric_Vehicle_Population_Data.csv")

df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,7.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,37.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,23.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,2.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10

In [2]:
df.shape

df.columns

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 279780 entries, 0 to 279779
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         279780 non-null  str
 1   County                                             279756 non-null  str
 2   City                                               279756 non-null  str
 3   State                                              279780 non-null  str
 4   Postal Code                                        279756 non-null  float64
 5   Model Year                                         279780 non-null  int64
 6   Make                                               279780 non-null  str
 7   Model                                              279780 non-null  str
 8   Electric Vehicle Type                              279780 non-null  str
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  279780 non-null  str
 10  Electric Range                                     279769 non-null  float64
 11  Legislative District                               279080 non-null  float64
 12  DOL Vehicle ID                                     279780 non-null  int64
 13  Vehicle Location                                   279671 non-null  str
 14  Electric Utility                                   279756 non-null  str
 15  2020 Census Tract                                  279756 non-null  float64
dtypes: float64(4), int64(2), str(10)
memory usage: 34.2 MB

어떤 차가 많이 등록돼 있을까? (제조사)

In [3]:
df["Make"].value_counts().head(10)

Make
TESLA         114847
CHEVROLET      19261
NISSAN         16164
FORD           15347
KIA            13938
TOYOTA         11827
BMW            11607
HYUNDAI        10357
RIVIAN          8863
VOLKSWAGEN      7449
Name: count, dtype: int64

모델 기준 Top 10

In [4]:
df["Model"].value_counts().head(10)

Model
MODEL Y           60035
MODEL 3           38137
LEAF              13533
MODEL S            7814
BOLT EV            7714
MODEL X            6940
MUSTANG MACH-E     6452
ID.4               6002
IONIQ 5            5978
R1S                5151
Name: count, dtype: int64

제조사 + 모델 조합

In [5]:
df.groupby(["Make", "Model"]).size().sort_values(ascending=False).head(15)

Make        Model
TESLA       MODEL Y              60035
            MODEL 3              38137
NISSAN      LEAF                 13533
TESLA       MODEL S               7814
CHEVROLET   BOLT EV               7714
TESLA       MODEL X               6940
FORD        MUSTANG MACH-E        6452
VOLKSWAGEN  ID.4                  6002
HYUNDAI     IONIQ 5               5978
RIVIAN      R1S                   5151
JEEP        WRANGLER              5014
TOYOTA      RAV4 PRIME (PHEV)     4757
KIA         NIRO                  4477
CHEVROLET   VOLT                  4449
FORD        F-150                 4100
dtype: int64

BEV vs PHEV 비교

In [6]:
df["Electric Vehicle Type"].value_counts()

df["Electric Vehicle Type"].value_counts(normalize=True) * 100

Electric Vehicle Type
Battery Electric Vehicle (BEV)            80.021445
Plug-in Hybrid Electric Vehicle (PHEV)    19.978555
Name: proportion, dtype: float64

제조사별 BEV vs PHEV 비교

In [7]:
pd.crosstab(df["Make"], df["Electric Vehicle Type"]).head(15)

Electric Vehicle Type,Battery Electric Vehicle (BEV),Plug-in Hybrid Electric Vehicle (PHEV)
Make,,
ACURA,356,0
ALFA ROMEO,0,104
AUDI,3898,2039
AZURE DYNAMICS,3,0
BENTLEY,0,10
BMW,5113,6494
BRIGHTDROP,51,0
CADILLAC,2349,85
CHEVROLET,14812,4449
CHRYSLER,0,3904
DODGE,120,708
FIAT,854,0
FISKER,133,9
FORD,11451,3896
GENESIS,504,0

특정 조건 필터링 (예: TESLA만)

In [8]:
df[df["Make"] == "TESLA"].head()

df[df["Make"] == "TESLA"]["Model"].value_counts()

Model
MODEL Y       60035
MODEL 3       38137
MODEL S        7814
MODEL X        6940
CYBERTRUCK     1874
ROADSTER         47
Name: count, dtype: int64

주행거리 기준 Top 10

In [9]:
df.sort_values(by="Electric Range", ascending=False)[
    ["Make", "Model", "Model Year", "Electric Range", "City"]
].head(10)

         Make    Model  Model Year  Electric Range            City
133173  TESLA  MODEL S        2020           337.0        Kirkland
110965  TESLA  MODEL S        2020           337.0      Lake Tapps
230211  TESLA  MODEL S        2020           337.0  Spokane Valley
77268   TESLA  MODEL S        2020           337.0         Spokane
264831  TESLA  MODEL S        2020           337.0          Tacoma
135606  TESLA  MODEL S        2020           337.0         Seattle
135434  TESLA  MODEL S        2020           337.0    Lake Stevens
163428  TESLA  MODEL S        2020           337.0        Kirkland
234287  TESLA  MODEL S        2020           337.0         Everett
12534   TESLA  MODEL S        2020           337.0         Seattle

주행거리 300 이상

In [10]:
df.sort_values(by="Electric Range", ascending=False)[
    ["Make", "Model", "Model Year", "Electric Range", "City"]
].head(10)

         Make    Model  Model Year  Electric Range            City
133173  TESLA  MODEL S        2020           337.0        Kirkland
110965  TESLA  MODEL S        2020           337.0      Lake Tapps
230211  TESLA  MODEL S        2020           337.0  Spokane Valley
77268   TESLA  MODEL S        2020           337.0         Spokane
264831  TESLA  MODEL S        2020           337.0          Tacoma
135606  TESLA  MODEL S        2020           337.0         Seattle
135434  TESLA  MODEL S        2020           337.0    Lake Stevens
163428  TESLA  MODEL S        2020           337.0        Kirkland
234287  TESLA  MODEL S        2020           337.0         Everett
12534   TESLA  MODEL S        2020           337.0         Seattle

BEV만 주행거리 Top 10

In [11]:
df[df["Electric Range"] >= 300][
    ["Make", "Model", "Electric Range"]
].sort_values(by="Electric Range", ascending=False)

         Make    Model  Electric Range
221079  TESLA  MODEL S           337.0
223656  TESLA  MODEL S           337.0
1375    TESLA  MODEL S           337.0
67652   TESLA  MODEL S           337.0
61452   TESLA  MODEL S           337.0
...       ...      ...             ...
218848  TESLA  MODEL 3           308.0
218626  TESLA  MODEL 3           308.0
217996  TESLA  MODEL 3           308.0
221525  TESLA  MODEL 3           308.0
221263  TESLA  MODEL 3           308.0

[2596 rows x 3 columns]

복합 조건 필터링

예: 2020년 이후 + BEV + 200km 이상

In [12]:
df[
    (df["Model Year"] >= 2020) &
    (df["Electric Vehicle Type"] == "Battery Electric Vehicle (BEV)") &
    (df["Electric Range"] >= 200)
][["Make", "Model", "Model Year", "Electric Range", "City"]]

             Make    Model  Model Year  Electric Range           City
14          TESLA  MODEL 3        2020           308.0          Lacey
19      CHEVROLET  BOLT EV        2020           259.0       Lynnwood
29      CHEVROLET  BOLT EV        2020           259.0          Lacey
30          TESLA  MODEL Y        2020           291.0       Lynnwood
42          TESLA  MODEL 3        2020           322.0      Snohomish
...           ...      ...         ...             ...            ...
279683      TESLA  MODEL X        2020           293.0        Seattle
279687      TESLA  MODEL 3        2020           266.0       Enumclaw
279701      TESLA  MODEL X        2020           293.0  Battle Ground
279714    PORSCHE   TAYCAN        2021           203.0          Camas
279749      TESLA  MODEL Y        2020           291.0       Bellevue

[10286 rows x 5 columns]

도시별 등록 대수

In [13]:
df["City"].value_counts().head(15)

City
Seattle       43250
Bellevue      13685
Vancouver     10395
Redmond        9606
Bothell        9239
Kirkland       7978
Sammamish      7798
Renton         7647
Olympia        6510
Tacoma         6072
Kent           4813
Spokane        4656
Bellingham     4612
Lynnwood       4581
Everett        4421
Name: count, dtype: int64

특정 도시 분석 (Seattle)

In [14]:
df[df["City"] == "Seattle"].head()

df[df["City"] == "Seattle"].shape[0]

43250

도시별 + 차종 비교

In [15]:
pd.crosstab(df["City"], df["Electric Vehicle Type"])

city = pd.crosstab(df["City"], df["Electric Vehicle Type"])
city["Total"] = city.sum(axis=1)

city.sort_values(by="Total", ascending=False).head(15)

Electric Vehicle Type,Battery Electric Vehicle (BEV),Plug-in Hybrid Electric Vehicle (PHEV),Total
City,,,
Seattle,34624,8626,43250
Bellevue,11876,1809,13685
Vancouver,7804,2591,10395
Redmond,8418,1188,9606
Bothell,8066,1173,9239
Kirkland,6760,1218,7978
Sammamish,6848,950,7798
Renton,5864,1783,7647
Olympia,5035,1475,6510
Tacoma,4653,1419,6072
Kent,4027,786,4813
Spokane,3391,1265,4656
Bellingham,3451,1161,4612
Lynnwood,4011,570,4581
Everett,3584,837,4421

특정 도시 + 제조사

In [16]:
df[df["City"] == "Bellevue"]["Make"].value_counts().head(10)

Make
TESLA            7749
BMW               797
NISSAN            601
CHEVROLET         465
KIA               383
RIVIAN            379
HYUNDAI           334
FORD              328
MERCEDES-BENZ     313
VOLVO             311
Name: count, dtype: int64

복합 필터 (실전 느낌)

예: Seattle + TESLA + BEV

In [17]:
df[
    (df["City"] == "Seattle") &
    (df["Make"] == "TESLA") &
    (df["Electric Vehicle Type"] == "Battery Electric Vehicle (BEV)")
][["Make", "Model", "Electric Range", "City"]].head(20)

      Make    Model  Electric Range     City
43   TESLA  MODEL 3           215.0  Seattle
53   TESLA  MODEL 3           215.0  Seattle
69   TESLA  MODEL 3           215.0  Seattle
77   TESLA  MODEL 3           215.0  Seattle
105  TESLA  MODEL Y           291.0  Seattle
127  TESLA  MODEL 3           220.0  Seattle
154  TESLA  MODEL 3           308.0  Seattle
243  TESLA  MODEL 3           220.0  Seattle
248  TESLA  MODEL S           210.0  Seattle
287  TESLA  MODEL 3           215.0  Seattle
290  TESLA  MODEL 3           215.0  Seattle
314  TESLA  MODEL 3           215.0  Seattle
327  TESLA  MODEL 3           215.0  Seattle
389  TESLA  MODEL 3           215.0  Seattle
436  TESLA  MODEL Y             0.0  Seattle
470  TESLA  MODEL Y             0.0  Seattle
474  TESLA  MODEL Y           291.0  Seattle
501  TESLA  MODEL S           208.0  Seattle
513  TESLA  MODEL 3             0.0  Seattle
517  TESLA  MODEL Y             0.0  Seattle

제조사별 평균 주행거리

In [18]:
df.groupby("Make")["Electric Range"].mean().sort_values(ascending=False).head(15)

Make
JAGUAR                  168.420382
WHEEGO ELECTRIC CARS    100.000000
TH!NK                   100.000000
CHEVROLET                77.942474
FIAT                     73.745902
NISSAN                   63.680525
SMART                    61.605150
AZURE DYNAMICS           56.000000
TESLA                    51.346888
LAND ROVER               51.000000
PORSCHE                  48.859281
AUDI                     36.742294
ALFA ROMEO               33.000000
BENTLEY                  33.000000
MITSUBISHI               32.641673
Name: Electric Range, dtype: float64

모델별 평균 주행거리

In [19]:
df.groupby(["Make", "Model"])["Electric Range"].mean().sort_values(ascending=False).head(15)

Make                  Model
TESLA                 ROADSTER            230.212766
JAGUAR                I-PACE              168.420382
CHEVROLET             BOLT EV             166.000907
TESLA                 MODEL S             162.140901
AUDI                  E-TRON              123.622912
TESLA                 MODEL X             111.577666
VOLKSWAGEN            E-GOLF              107.459302
TOYOTA                RAV4                102.714286
TH!NK                 CITY                100.000000
WHEEGO ELECTRIC CARS  WHEEGO              100.000000
AUDI                  E-TRON SPORTBACK     96.669683
KIA                   SOUL                 94.765018
PORSCHE               MACAN                94.081505
BMW                   I3                   90.556800
MERCEDES-BENZ         B-CLASS              87.000000
Name: Electric Range, dtype: float64

깔끔한 요약 출력

In [20]:
print("Top Makes:\n", df["Make"].value_counts().head(), "\n")

print("Top Models:\n", df["Model"].value_counts().head(), "\n")

print("EV Type:\n", df["Electric Vehicle Type"].value_counts(), "\n")

print("Top Cities:\n", df["City"].value_counts().head())

Top Makes:
 Make
TESLA        114847
CHEVROLET     19261
NISSAN        16164
FORD          15347
KIA           13938
Name: count, dtype: int64

Top Models:
 Model
MODEL Y    60035
MODEL 3    38137
LEAF       13533
MODEL S     7814
BOLT EV     7714
Name: count, dtype: int64

EV Type:
 Electric Vehicle Type
Battery Electric Vehicle (BEV)            223884
Plug-in Hybrid Electric Vehicle (PHEV)     55896
Name: count, dtype: int64

Top Cities:
 City
Seattle      43250
Bellevue     13685
Vancouver    10395
Redmond       9606
Bothell       9239
Name: count, dtype: int64